name: ESLint Code check
on:
  push:
    branches:
      - "main"
      - "release"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install package manager
        run: yarn

      - name: Run ESLint
        run: eslint . --ext .ts , .js
