name: ESLint Code check
on:
  push:
    branches:
      - "main"
      - "release"
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install npm
        run: npm ci

      - name: Install eslint-plugin-react
        run: npm install eslint-plugin-react@latest --save-dev

      - name: Run ESLint suggestion
        run: npm run lint
